// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// multipleCpp
Eigen::MatrixXd multipleCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y);
RcppExport SEXP _RISC_multipleCpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(multipleCpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// crossprodCpp
Eigen::MatrixXd crossprodCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y);
RcppExport SEXP _RISC_crossprodCpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodCpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprodCpp
Eigen::MatrixXd tcrossprodCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y);
RcppExport SEXP _RISC_tcrossprodCpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprodCpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// selfcrossprodCpp
Eigen::MatrixXd selfcrossprodCpp(Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _RISC_selfcrossprodCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(selfcrossprodCpp(A));
    return rcpp_result_gen;
END_RCPP
}
// selftcrossprodCpp
Eigen::MatrixXd selftcrossprodCpp(Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _RISC_selftcrossprodCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(selftcrossprodCpp(A));
    return rcpp_result_gen;
END_RCPP
}
// svdCpp
List svdCpp(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _RISC_svdCpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(svdCpp(X));
    return rcpp_result_gen;
END_RCPP
}
// QRsolveCpp
Eigen::MatrixXd QRsolveCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y);
RcppExport SEXP _RISC_QRsolveCpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(QRsolveCpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// lmCpp
Eigen::VectorXd lmCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::VectorXd> y);
RcppExport SEXP _RISC_lmCpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(lmCpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// simplsCpp
List simplsCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y, int ncomp);
RcppExport SEXP _RISC_simplsCpp(SEXP XSEXP, SEXP YSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(simplsCpp(X, Y, ncomp));
    return rcpp_result_gen;
END_RCPP
}
// svdpcrCpp
List svdpcrCpp(Eigen::Map<Eigen::MatrixXd>& X, Eigen::Map<Eigen::MatrixXd>& Y, int ncomp);
RcppExport SEXP _RISC_svdpcrCpp(SEXP XSEXP, SEXP YSEXP, SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(svdpcrCpp(X, Y, ncomp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RISC_multipleCpp", (DL_FUNC) &_RISC_multipleCpp, 2},
    {"_RISC_crossprodCpp", (DL_FUNC) &_RISC_crossprodCpp, 2},
    {"_RISC_tcrossprodCpp", (DL_FUNC) &_RISC_tcrossprodCpp, 2},
    {"_RISC_selfcrossprodCpp", (DL_FUNC) &_RISC_selfcrossprodCpp, 1},
    {"_RISC_selftcrossprodCpp", (DL_FUNC) &_RISC_selftcrossprodCpp, 1},
    {"_RISC_svdCpp", (DL_FUNC) &_RISC_svdCpp, 1},
    {"_RISC_QRsolveCpp", (DL_FUNC) &_RISC_QRsolveCpp, 2},
    {"_RISC_lmCpp", (DL_FUNC) &_RISC_lmCpp, 2},
    {"_RISC_simplsCpp", (DL_FUNC) &_RISC_simplsCpp, 3},
    {"_RISC_svdpcrCpp", (DL_FUNC) &_RISC_svdpcrCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RISC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
