# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrt_sp <- function(X) {
    .Call('_RISC_sqrt_sp', PACKAGE = 'RISC', X)
}

cent_sp_d <- function(X) {
    .Call('_RISC_cent_sp_d', PACKAGE = 'RISC', X)
}

multiply_sp_sp <- function(X, Y) {
    .Call('_RISC_multiply_sp_sp', PACKAGE = 'RISC', X, Y)
}

multiply_sp_d <- function(X, Y) {
    .Call('_RISC_multiply_sp_d', PACKAGE = 'RISC', X, Y)
}

multiply_d_d <- function(X, Y) {
    .Call('_RISC_multiply_d_d', PACKAGE = 'RISC', X, Y)
}

multiply_sp_d_sp <- function(X, Y) {
    .Call('_RISC_multiply_sp_d_sp', PACKAGE = 'RISC', X, Y)
}

multiply_sp_d_v <- function(X, Y) {
    .Call('_RISC_multiply_sp_d_v', PACKAGE = 'RISC', X, Y)
}

crossprod_sp_sp <- function(X, Y) {
    .Call('_RISC_crossprod_sp_sp', PACKAGE = 'RISC', X, Y)
}

crossprod_sp_d <- function(X, Y) {
    .Call('_RISC_crossprod_sp_d', PACKAGE = 'RISC', X, Y)
}

crossprod_d_d <- function(X, Y) {
    .Call('_RISC_crossprod_d_d', PACKAGE = 'RISC', X, Y)
}

tcrossprod_sp_sp <- function(X, Y) {
    .Call('_RISC_tcrossprod_sp_sp', PACKAGE = 'RISC', X, Y)
}

tcrossprod_d_d <- function(X, Y) {
    .Call('_RISC_tcrossprod_d_d', PACKAGE = 'RISC', X, Y)
}

winsorize_ <- function(x, y) {
    .Call('_RISC_winsorize_', PACKAGE = 'RISC', x, y)
}

lm_coef <- function(X, y) {
    .Call('_RISC_lm_coef', PACKAGE = 'RISC', X, y)
}

lm_ <- function(X, y) {
    .Call('_RISC_lm_', PACKAGE = 'RISC', X, y)
}

