# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multipleCpp <- function(X, Y) {
    .Call('_RISC_multipleCpp', PACKAGE = 'RISC', X, Y)
}

crossprodCpp <- function(X, Y) {
    .Call('_RISC_crossprodCpp', PACKAGE = 'RISC', X, Y)
}

tcrossprodCpp <- function(X, Y) {
    .Call('_RISC_tcrossprodCpp', PACKAGE = 'RISC', X, Y)
}

selfcrossprodCpp <- function(A) {
    .Call('_RISC_selfcrossprodCpp', PACKAGE = 'RISC', A)
}

selftcrossprodCpp <- function(A) {
    .Call('_RISC_selftcrossprodCpp', PACKAGE = 'RISC', A)
}

svdCpp <- function(X) {
    .Call('_RISC_svdCpp', PACKAGE = 'RISC', X)
}

QRsolveCpp <- function(X, Y) {
    .Call('_RISC_QRsolveCpp', PACKAGE = 'RISC', X, Y)
}

lmCpp <- function(X, y) {
    .Call('_RISC_lmCpp', PACKAGE = 'RISC', X, y)
}

simplsCpp <- function(X, Y, ncomp) {
    .Call('_RISC_simplsCpp', PACKAGE = 'RISC', X, Y, ncomp)
}

svdpcrCpp <- function(X, Y, ncomp) {
    .Call('_RISC_svdpcrCpp', PACKAGE = 'RISC', X, Y, ncomp)
}

